// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzodwbgidgfmxjhzyrog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6b2R3YmdpZGdmbXhqaHp5cm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NTA2MDUsImV4cCI6MjA1MjUyNjYwNX0.Cfmea8bWqMF95nEKe8DiUqRAv-wEnmIhWubqHqOQTJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);